# Generated by Django 5.1.7 on 2025-04-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_canditate',
            field=models.BooleanField(default=False),
        ),
    ]
