# Generated by Django 5.1.7 on 2025-04-27 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='level',
        ),
        migrations.AddField(
            model_name='position',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='election.college'),
        ),
        migrations.AddField(
            model_name='position',
            name='hostel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='election.hostel'),
        ),
        migrations.AddField(
            model_name='position',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='election.university'),
        ),
        migrations.AlterField(
            model_name='leaderpromise',
            name='promise',
            field=models.TextField(blank=True, null=True),
        ),
    ]
