# Generated by Django 5.1.7 on 2025-04-27 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0002_student_is_canditate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='is_canditate',
            new_name='is_candidate',
        ),
    ]
