# Generated by Django 5.1.7 on 2025-04-27 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0003_rename_is_canditate_student_is_candidate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='registration_number',
        ),
    ]
