# Generated by Django 5.1.7 on 2025-04-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0004_remove_student_registration_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='academic_year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
