# Generated by Django 5.1.7 on 2025-04-27 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0005_candidate_academic_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='academic_year',
        ),
    ]
