# Generated by Django 5.1.7 on 2025-04-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0006_remove_candidate_academic_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='positions',
            field=models.ManyToManyField(related_name='elections', through='election.ElectionPosition', to='election.position'),
        ),
    ]
