# Generated by Django 5.1.7 on 2025-06-11 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0008_alter_promiseupdate_promise_alter_vote_candidate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electionposition',
            name='ai_fraud_indicators',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electionposition',
            name='ai_fraud_risk',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='electionposition',
            name='ai_last_analysis',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electionposition',
            name='ai_prediction_confidence',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='electionposition',
            name='ai_win_prediction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predicted_wins', to='election.candidate'),
        ),
    ]
