# Generated by Django 5.1.7 on 2025-06-16 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0009_electionposition_ai_fraud_indicators_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elections', to='election.institution'),
        ),
    ]
