# Generated by Django 5.1.7 on 2025-06-16 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0010_alter_election_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='election_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='election.electionposition'),
        ),
    ]
