# Generated by Django 5.1.7 on 2025-06-16 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0011_alter_candidate_election_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='election_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.electionposition'),
        ),
        migrations.AlterField(
            model_name='election',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='election.institution'),
        ),
    ]
